# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self

- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(agent.builddirectory)'
    Contents: '**'
    TargetFolder: '$(build.artifactstagingdirectory)'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- script: |
    set -x
    # Instaluje Docker i Docker Compose
    sudo apt-get update
    sudo apt-get install -y docker.io
    sudo apt-get install -y docker-compose

    # Buduje i wdraża kontenery za pomocą docker-compose
    docker-compose -f $(System.DefaultWorkingDirectory)/.yml build
    docker-compose -f $(System.DefaultWorkingDirectory)/*.yml push
  displayName: 'Build and push Docker containers'
